require "./inflector/inflections"

module LuckyInflector
  inflections.plural(/$/, "s")
  inflections.plural(/s$/i, "s")
  inflections.plural(/^(ax|test)is$/i, "\\1es")
  inflections.plural(/(octop|vir)us$/i, "\\1i")
  inflections.plural(/(octop|vir)i$/i, "\\1i")
  inflections.plural(/(alias|status)$/i, "\\1es")
  inflections.plural(/(bu)s$/i, "\\1ses")
  inflections.plural(/(buffal|tomat)o$/i, "\\1oes")
  inflections.plural(/([ti])um$/i, "\\1a")
  inflections.plural(/([ti])a$/i, "\\1a")
  inflections.plural(/sis$/i, "ses")
  inflections.plural(/(?:([^f])fe|([lr])f)$/i, "\\1\\2ves")
  inflections.plural(/(hive)$/i, "\\1s")
  inflections.plural(/([^aeiouy]|qu)y$/i, "\\1ies")
  inflections.plural(/(x|ch|ss|sh)$/i, "\\1es")
  inflections.plural(/(matr|vert|ind)(?:ix|ex)$/i, "\\1ices")
  inflections.plural(/^(m|l)ouse$/i, "\\1ice")
  inflections.plural(/^(m|l)ice$/i, "\\1ice")
  inflections.plural(/^(ox)$/i, "\\1en")
  inflections.plural(/^(oxen)$/i, "\\1")
  inflections.plural(/(quiz)$/i, "\\1zes")

  inflections.singular(/s$/i, "")
  inflections.singular(/(ss)$/i, "\\1")
  inflections.singular(/(n)ews$/i, "\\1ews")
  inflections.singular(/([ti])a$/i, "\\1um")
  inflections.singular(/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)(sis|ses)$/i, "\\1sis")
  inflections.singular(/(^analy)(sis|ses)$/i, "\\1sis")
  inflections.singular(/([^f])ves$/i, "\\1fe")
  inflections.singular(/(hive)s$/i, "\\1")
  inflections.singular(/(tive)s$/i, "\\1")
  inflections.singular(/([lr])ves$/i, "\\1f")
  inflections.singular(/([^aeiouy]|qu)ies$/i, "\\1y")
  inflections.singular(/(s)eries$/i, "\\1eries")
  inflections.singular(/(m)ovies$/i, "\\1ovie")
  inflections.singular(/(x|ch|ss|sh)es$/i, "\\1")
  inflections.singular(/^(m|l)ice$/i, "\\1ouse")
  inflections.singular(/(bus)(es)?$/i, "\\1")
  inflections.singular(/(o)es$/i, "\\1")
  inflections.singular(/(shoe)s$/i, "\\1")
  inflections.singular(/(cris|test)(is|es)$/i, "\\1is")
  inflections.singular(/^(a)x[ie]s$/i, "\\1xis")
  inflections.singular(/(octop|vir)(us|i)$/i, "\\1us")
  inflections.singular(/(alias|status)(es)?$/i, "\\1")
  inflections.singular(/^(ox)en/i, "\\1")
  inflections.singular(/(vert|ind)ices$/i, "\\1ex")
  inflections.singular(/(matr)ices$/i, "\\1ix")
  inflections.singular(/(quiz)zes$/i, "\\1")
  inflections.singular(/(database)s$/i, "\\1")

  inflections.irregular("person", "people")
  inflections.irregular("man", "men")
  inflections.irregular("child", "children")
  inflections.irregular("sex", "sexes")
  inflections.irregular("move", "moves")
  inflections.irregular("zombie", "zombies")

  inflections.uncountable(%w(equipment information rice money species series fish sheep jeans police))
end
